plugins {
    alias(libs.plugins.spring.boot) apply false
    alias(libs.plugins.spring.dependency.management) apply false
}

allprojects {
    group = 'fi.poltsi.vempain'
    version = libs.versions.release.get()
}

subprojects {
    apply plugin: 'io.spring.dependency-management'

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:${libs.versions.spring.boot.get()}"
        }
    }

    plugins.withId('java') {
        java {
            sourceCompatibility = JavaVersion.toVersion(libs.versions.java.get())
            targetCompatibility = JavaVersion.toVersion(libs.versions.java.get())
        }
    }
}
