plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
	id 'jacoco'
}

group = 'fi.poltsi.vempain'
version = project.hasProperty("releaseVersion") ? project.releaseVersion : '0.0.1-SNAPSHOT'

bootJar {
	archiveFileName = "${rootProject.name}-${version}.jar"
}

description = 'Vempain Website public backend (Spring Boot rewrite of the PHP backend)'

java {
    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

dependencies {
    implementation project(':api')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.security:spring-security-crypto'
	implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation "org.testcontainers:testcontainers-junit-jupiter:${testContainersVersion}"
	testImplementation "org.testcontainers:testcontainers-postgresql:${testContainersVersion}"
}

repositories {
	mavenCentral()
	maven {
		url = "https://maven.pkg.github.com/Vempain/vempain-auth"
		credentials {
			username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
			password = project.findProperty("gpr.token") ?: System.getenv("GITHUB_TOKEN")
		}
	}
	maven {
		url = "https://maven.pkg.github.com/Vempain/vempain-admin-backend-api"
		credentials {
			username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
			password = project.findProperty("gpr.token") ?: System.getenv("GITHUB_TOKEN")
		}
	}
	maven { url = 'https://repo.spring.io/milestone' }
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.required = true
		html.required = true
	}
}

jacocoTestCoverageVerification {
	dependsOn test
	violationRules {
		rule {
			element = 'PACKAGE'
			includes = ['fi.poltsi.vempain.file.service.files']
			limit {
				counter = 'LINE'
				value = 'COVEREDRATIO'
				minimum = 0.95
			}
		}
	}
}

tasks.named('test') {
    useJUnitPlatform()
    include '**/*UTC.class'
    include '**/*ITC.class'
    include '**/*CTC.class'
}

tasks.named('bootJar') {
    archiveFileName = 'vempain-website-backend.jar'
}
